name: Test

on: [push]

jobs:
  test:
    runs-on: windows-latest
    strategy:
       matrix:
         include:
           - platform: 'x86_64'
       fail-fast: false

    name: 'Test ${{ matrix.platform }}'

    steps:
    - run: git config --global core.autocrlf input

    - uses: actions/checkout@v2

    - uses: cygwin/cygwin-install-action@master

    - run: bash tests/script.sh
